name: fast_rx_jaspr_example
description: fast_rx_jaspr example app
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr: ^0.17.1
  fast_rx_jaspr:
    path: ../

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^4.0.3
  rexios_lints: ^10.0.1
  webdev: ^3.0.4