name: fast_rx_jaspr_example
description: fast_rx_jaspr example app
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  jaspr: ^0.3.0
  fast_rx_jaspr:
    path: ../

dev_dependencies:
  build_runner: ^2.2.0
  build_web_compilers: ^3.2.1
  rexios_lints: ^5.0.0
  webdev: ^2.7.12