name: fast_rx_jaspr
description: fast_rx, but for Jaspr
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  jaspr: ^0.1.5
  fast_rx: ^0.4.1

dev_dependencies:
  rexios_lints: ^4.0.0
  test: ^1.16.0
