name: Static Analysis
on:
  push:
  pull_request:

jobs:
  static-analysis:
    strategy:
      matrix:
        project:
          [
            "fast_rx_jaspr",
          ]
    defaults:
      run:
        working-directory: ${{ matrix.project }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: subosito/flutter-action@v2
      - name: Pub get
        run: flutter pub get
      - name: Format
        run: dart format . --set-exit-if-changed
      - name: Analyze
        run: dart analyze
      - name: Embedme
        run: |
          npm install embedme
          npx embedme README.md --verify
      # - name: Build runner
      #   if: ${{ matrix.project == 'fast_rx_test' }}
      #   run: |
      #     flutter pub run build_runner build --delete-conflicting-outputs
      #     git diff --exit-code
      - name: Pana
        run: |
          flutter pub global activate pana
          pana --no-warning --exit-code-threshold 0
